### ISSUE TITLE
Table rows should be fixed height by default

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#1]
... we could have some hover for by fields or the ability of increase of expand a row heights.
Bu the default to be as high as a tallest cell is visually weird

**Comment by pombredanne** [comment]
See also https://datatables.net/plug-ins/dataRender/ellipsis

**Comment by majurg** [comment]
#375 merged, closing this. Further enhancements and fixes regarding heights and ellipsis can be handled in new tickets.
