### ISSUE TITLE
Add reporting capabilities

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#138]
For the long term we need to think about adding reporting capabilities so that a user can extract a useful subset of data from a Scan file.  This could be based on exporting the results from your filtered view of  data or a separate reporting module. Presumably we could use something SQL-based since the scan files are now stored in SQLite.
This feature clearly needs more specific use cases, but we should start now with evaluation of a basic approach and research into any open source projects that might apply.

**Comment by majurg** [comment]
also from @mjherzog:
"We need a way to leverage the SQLite DB for analysis that does not easily fit within the UI (and without needing to use a separate tool like DB.Browser.for.SQLite"

**Comment by sairajsawant** [comment]
Can I take this up for GSOC 2020?

**Comment by steven-esser** [comment]
@sairajsawant yes

**Comment by OmkarPh** [comment]
Closing, as it is not applicable
