### ISSUE TITLE
Add support for Package Identification results

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-workbench#157]
The "DejaCode Package Identification" output has recently evolved. 

The identified packages are injected in the scan JSON output as a `packages` list.
A `match` entry is available including the `source` of the match, for example: `dejacode` or `packagedb`.

It'll great for AboutCode Manager to support those values.

Attaching an example of an identified scan, including the 2 match sources: 
[scancode_identified.json.zip](https://github.com/nexB/aboutcode-manager/files/1234918/scancode_identified.json.zip)

**Comment by OmkarPh** [comment]
Closing as this is no longer relevant
