### ISSUE TITLE
Column Visibility Options

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#164]
Originally from https://github.com/nexB/aboutcode-manager/issues/3#issuecomment-302791940 by @mjherzog:
 

> We need to enhance the Column Visibility options in the Table View. Some ideas:
> 1. Create an "Info set" option like "License Info" for each Model - currently missing Package and ?
> 2. Add a Fileinfo Info set - not sure that Fileinfo corresponds to a specific Model.
> 3. Define a minimal set of Fileinfo columns that are used in each Info set
> 4. Document primary Info subsets in the Column Visibility window - these appear to be already primarily sorted by Model (and in Help)

**Comment by mjherzog** [comment]
My original idea was to allow you to easily toggle Column Visibility for the primary datasets from a scan which would mean starting with Copyrights, Licenses and Packages as groups.  Within each dataset, there are primary/summary columns and secondary/detail - for example with Copyright I would consider Copyright Statements to be primary/summary and the other columns to be secondary/details in the sense that you first want to see the detected Copyright and then you may (or may not) want to see the supporting detail. 

Issue #3 seems to address the quickest way to focus the initial display columns and move from the "display all/ then reduce" approach to a "display few / then add" approach. The next-level solution should probably be to add a way for the user to save column sets (like saving a set of filters) and then we can pre-populate some suggested column sets.  This should be a better solution than "hard-coding" column-sets.

**Comment by mjherzog** [comment]
@majurg I think that we can close this issue if we add Type to the File info column set.

**Comment by majurg** [comment]
@mjherzog `Type` has been added to the file info column set. Closing this.
