### ISSUE TITLE
Add support for searching only the file paths in the file tree

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-workbench#173]
This would help a lot to focus on certain files only with a path or name that matches a search string. The best similarity would the Github "find files" feature 

The way I am thinking of this would be a new search box that would search and filter on the tree side may be or both the table and tree.

**Comment by jdaguil** [comment]
jsTree has a [Search plugin](https://www.jstree.com/plugins/#plugins4_q) which adds a search box for the tree. It's probably easier if you provide all the data at once. However, our tree is backed by the database, and we only provide the data it needs when it's needed. i.e. we only search for the children when you open the parent directory. I'm not sure what the implementation would be to enable this.

**Comment by OmkarPh** [comment]
Update - This is being experimented in [improve/depth-based-tableview-sort](https://github.com/nexB/scancode-workbench/tree/improve/depth-based-tableview-sort)

**Comment by OmkarPh** [comment]
Closing this, as discussed & resolved in #625
