### ISSUE TITLE
Show concluded information in table view

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#18]
Currently, when a component is created, concluded information (license, owner, copyright etc) is not shown in the table view.

**Comment by jdaguil** [comment]
Currently, this information is shown in the Component Summary Table. Adding it to the Clues Table View would mean having mutable data in the `flat_files` table. Currently, the `flat_files` table is read-only. Since this data is also kept in the `components` table it would have to be kept in sync across both tables. This seems like it could lead to issues. 

Another option is to somehow merge the `components` table information with the `flat_files` information when rendering the DataTables. However, this will be difficult because DataTables is meant to work for a single table. 

This is related to #209.

**Comment by mjherzog** [comment]
Closing because we are deprecating Conclusions in SCWB in favor of building a more robust feature in SCIO.
