### ISSUE TITLE
Import multiple scans in a single DB

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-workbench#180]
This would be a great feature and support doing multiple smaller, package-level scans.

**Comment by pombredanne** [comment]
This is a replacement for https://github.com/nexB/scancode-toolkit/issues/585 by @kalagp

**Comment by majurg** [comment]
I agree, being able to 'append' the root dir of a entirely new scan to an already active sqlite db file would be awesome.

**Comment by mjherzog** [comment]
Closing because it is a workaround for problems that should be resolved in SCTK.
