### ISSUE TITLE
Add essential columns group to table view 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-workbench#189]
The idea would be to have a simpler column group that shows the important columns on origin/license/etc and leaves out many of the technical columns (e.g. line numbers, etc)

**Comment by mjherzog** [comment]
This would need to be some customizable setting since the definition of "essential" likely varies by user / usage.

**Comment by jdaguil** [comment]
We currently have the Origin info group button which attempts to achieve this. Do you have another set of columns in mind? Otherwise, this might be addressed in https://github.com/nexB/aboutcode-manager/issues/164

**Comment by majurg** [comment]
This was addressed in #164. Closing.
