### ISSUE TITLE
Submit AboutCode Manager to Electron Applications 

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#216]
Submit AboutCode Manager to Electron's list of Apps. See https://github.com/electron/electron-apps/blob/master/contributing.md

**Comment by vsvipul** [comment]
Opened a PR related to this here 
https://github.com/electron/apps/pull/987

**Comment by vsvipul** [comment]
@majurg this can be closed, i guess

**Comment by majurg** [comment]
@vsvipul Thanks.
