### ISSUE TITLE
Handle schema migrations

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#230]
### Description
We need to handle database schema changes. Currently, we only throw an error if the header table is not present, but ideally we would be able to migrate the old database to the new schema automatically based on the version of AboutCode Manager used to create the old database, or we'd give a more specific error message corresponding to the exact version where the error occurred.

Migrating a database from an old version, _Vi_, to a new version, _Vj_, would work by first defining migration steps between every successive version of AboutCode Manager. Then, we could migrate a database from _Vi_ to _Vj_ by migrating one step at a time: `Vi -> Vi+1 -> Vi+2 -> ... -> Vj-1 -> Vj`.

See also #228

### Steps to reproduce
Note this is just one example.
1. Import a scan into v2.30 of AboutCode Manager.
2. Choose a SQLite file name to save.
3. Download and open v2.4.0 of AboutCode Manager.
4. Open the SQLite file create from step 2.

**Expected behavior**
App allows the user to import any SQLite file created from any version of the app, and it handles the migration for the user without error.

**Actual behavior**
Either an error occurs (i.e. new table added such as the header table) or the app functions normally with a silent failure (i.e. ScanCode adds a new attribute)

**Reproduces how often:** 
Whenever a user imports a SQLite file created in a different version than the version they are currently using.

### System configuration
**Operating System**:
Mac, Linux, Windows

**AboutCode Manager Version**:
All versions (current version of app when this issue is created is 2.4.0)

**Comment by OmkarPh** [comment]
We won't migrate sqlite DB, it is better to reimport the scans in the newer version
Hence, closing as won't fix
