### ISSUE TITLE
Results detected from ScanCode should be pre-populated in the conclusion pop-up

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-workbench#242]
When I open a conclusion pop-up, the detected ScanCode values should be pre-populated if I did not save a conclusion before
- if there is only one value it should be picked
- if there are more than one value, they should be aggregated as a license expression or composite copyright or the main one should be picked
  - a component name should be suggested

**Comment by steven-esser** [comment]
This goes alongside #270

**Comment by pombredanne** [comment]
IMHO we should reconsider the conclusions features to use instead ScanCode.io for a more comprehensive approach.

**Comment by mjherzog** [comment]
Closing because we are deprecating the Conclusions feature in favor of building it into SCIO.
