### ISSUE TITLE
Fix column display to keep columns visible when navigating among pages

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#253]
If the column selection is set to display enough columns to require a horizontal scrollbar, and the column of interest requires dragging the horizontal scrollbar to display a column on the right, navigating from page to page often resets the display so that the column of interest is no longer visible and the user must repeatedly reset the horizontal scrollbar while paging.  I'm not positive but suspect this is a result of the columns not having a fixed width.

**Comment by majurg** [comment]
#377 merged, closing this.
