### ISSUE TITLE
ClueDataTables: Long path names should wrap to next line sooner

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-workbench#263]
![screen shot 2018-07-17 at 2 18 11 pm](https://user-images.githubusercontent.com/7485204/42845956-58a67d20-89cc-11e8-97a3-912340794aee.png)

Many cases, long path names take up the majority of the horizontal screen space in the Clues data tables. 

As you can see from the pic, path strings do wrap after a certain amount of characters but we want this character length to be reduced so we can fit more columns on the screen when path strings are long.

**Comment by mjherzog** [comment]
What is the current number of characters that forces a wrap?

**Comment by majurg** [comment]
Relevant link to a possible solution: https://datatables.net/forums/discussion/26629/how-to-set-word-wrap-and-limit-column-width-while-altering-visibility

**Comment by pombredanne** [comment]
And we should also have fixed height and IMHO ellipsis on long paths or values per #1

**Comment by majurg** [comment]
#375 merged, closing this. Further enhancements and fixes regarding heights and ellipsis can be handled in new tickets.
