### ISSUE TITLE
Consider a new and/or modified method to create/edit Conclusions

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#270]
The sole current method to create/edit a Conclusion is by right-clicking a node in the Treeview and selecting `Edit Component` (the naming convention is in transition -- this may become `Edit Conclusion`).  When that option is selected, a modal window opens, which contains a form with editable elements (textboxes, radio button groups and dropdowns).

It could be useful to provide one or more additional methods to create/edit a Conclusion.  One possible approach: modify the `Component Summary View` (which may be renamed `Conclusions View`) so that each row is editable in line.

This issue overlaps and should supersede issue #128.

**Comment by steven-esser** [comment]
Consolidations could possibly become conclusions automatically when a scan is loaded.

**Comment by johnmhoran** [comment]
@majurg I don't use ScanCode Workbench to create Conclusions so I don't know if this issue remains relevant, but I suspect the Conclusion process has changed since I opened this issue.  I'm inclined to close this unless you think it should stay open.

**Comment by steven-esser** [comment]
@johnmhoran good point, we have #242 and #390 which are more the direction we want to go with w.r.t. conclusions.

Doing them by hand will still be an option, but it will never be as practical as the above issues once completed.
