### ISSUE TITLE
Move filter bar to top of page

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#271]
The bar with column filters is currently displayed at the bottom of the Table View window, separate from the Column visibility and Search buttons at the top. It might be more logical and useful to display the Filter bar below the current Column visibility / Search bar.

**Comment by majurg** [comment]
This can be done, however I am concerned we will have a lot of stuff at the top of tables with the column visibility buttons being there as well. 

Perhaps those can be made smaller in some way.

**Comment by lakshay-angrish** [comment]
@mjherzog @majurg If you're not working on this, could you assign it to me?
