### ISSUE TITLE
Add Welcome Page

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#290]
It is a bit confusing  when you start up AbC Manager and first see a Dashboard page with no data. Since AbC Manager does not save/display your last project (and I am not suggesting that it should), AbC Mgr should display a Welcome page which could include information, such as:
- Very simple documentation about how to get started - i.e. you need a ScanCode .json data file
- Import the file
- Adjust Column Visibility 
- etc.
It could be good to also display release notes. 
MS Visual Studio Code offers a pretty good example of the idea. We can start simpler and look to add features like Recent Scans over time.

![visualstudocode welcome](https://user-images.githubusercontent.com/4853767/44487114-4e662180-a60a-11e8-9aa4-47a38bf4aede.png)

**Comment by majurg** [comment]
I agree, having a "landing" page with some documentation, release notes etc would go a long way usability-wise for AboutCode-Manager.

**Comment by majurg** [comment]
#340 Merged.

An initial Welcome Page has been created. We can handle additional feature requests and changes in new tickets. For now I will close this.
