### ISSUE TITLE
Blank space on BarChart view

### ISSUE THREAD

**Issue by steven-esser** [nexB/scancode-workbench#292]
<img width="1988" alt="screen shot 2018-08-24 at 6 30 18 pm" src="https://user-images.githubusercontent.com/7485204/44613682-de06fe00-a7cb-11e8-8eca-65b551e039a9.png">

As you can see from the above picture, there is a large blank space that shows up occasionally on the Bar Chart view. It seems the more items on the Bar Chart, the more blank space there is. 

Ultimately, we need to git rid of this white space. It is not useful at all, and makes scrolling around in this view much worse UX-wise.

**Comment by vsvipul** [comment]
@majurg  is this fixed? if not, how can i reproduce this ?

**Comment by steven-esser** [comment]
This can be reproduced with large scans that contain many data points on the bar chart. It seems like the total number of items being displayed on the bar chat effects the size of this blank/white space in some way.

**Comment by OmkarPh** [comment]
Closing this, as it is not applicable with the latest versions (The drawing is handled by chart.js and works fine)
