### ISSUE TITLE
Need to refresh Table View (and others) on Import of JSON file

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#293]
While we are in a period of frequent updates to AbC Mgr and ScanCode TK for Packages and other new feature, I need to frequently rebuild a SQLite file from the JSON scan file. When you have a SQLite file A loaded and Import a new JSON file B, AbC Mgr still displays the Table View from the the SQLite file A.  

**Expected behavior**
When you Import a JSON file, the Table View (and other Views) should be cleared as soon as you start the Import. It is confusing to see the "old" Table View data displayed.

**Actual behavior**
AbC Manager usually display the "old" Table View until the new SQLite file is fully loaded. If there is an error during Import, the "old" Table View remains.

**Reproduces how often:** 
Not completely consistent, but occurs most often when you need to re-Import a JSON file to use one from most current version of ScanCode.

**AboutCode Manager Version**:
AboutCode-Manager-windows-x64-2.5.0.post7.c220dd2

**Comment by majurg** [comment]
#333 merged, closing this.
