### ISSUE TITLE
Strange behavior when pressing Edit Conclusion for "busybox-1.29.2" sample scan

### ISSUE THREAD

**Issue by steven-esser** [nexB/scancode-workbench#298]
<img width="1988" alt="screen shot 2018-08-31 at 12 57 17 pm" src="https://user-images.githubusercontent.com/7485204/44934408-8d3e5a80-ad21-11e8-9ac0-1b5cd1f065fc.png">

This only occurs when trying to create a Conclusion at the root directory level of this `busybox-1.29.2-scan.json` found in the samples/ dir of ABCM. I can successfully create conclusions at any other level in the tree, so it is something unique about the root dir.

**Comment by mjherzog** [comment]
Closing because we are deprecating the Conclusions feature.
