### ISSUE TITLE
Streamline left panel

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#306]
The File Open and File Save icons/buttons at the top of the left panel are somewhat confusing vs the File menu.
Without mouse-over help, it is not clear what type of file you can Open (only SQLite) and what Save means (Save As for SQLite file only). 
The Help icon/button on the left panel is also confusing because it is different from the Help menu items.

I suggest that we:
- Remove move the File Open and Save As buttons from the left panel - this means that all of the buttons/icons will be Views (and they already have mouse-over names). The File menu already covers all the current supported actions.
- Move the Help window from the left panel to the top of the Help Menu - this may require some design for the Help Menu.

**Comment by majurg** [comment]
#340 Merged, which handles moving a few sidebar buttons to the new Welcome Page.

Further sidebar adjustments can be handled in new tickets; for now I am closing this.
