### ISSUE TITLE
Add new Travis Windows support to CI loop

### ISSUE THREAD

**Issue by steven-esser** [nexB/scancode-workbench#312]
Now that travis has Windows support, we should consolidate and use that.

**Comment by steven-esser** [comment]
We may want to add azure-pipeline support here as well.

**Comment by OmkarPh** [comment]
In the latest version, releases are being handled by Github actions
CC @mjherzog @pombredanne

**Comment by OmkarPh** [comment]
now that we have all builds on Github actions, can we close this issue?
@AyanSinhaMahapatra

**Comment by OmkarPh** [comment]
Closing this as we've shifted to Github actions, hence Travis CI is no longer needed
