### ISSUE TITLE
Column filter boxes disappear working with large sqlite file

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#316]
Working with a 500+ MB sqlite file, I've just seen one instance of the column filters disappearing after successfully using them and then navigating to a different node in the tree.  I can see and click the `Activate Filters` and `Clear Filters` buttons, but not the filters themselves.  Have not seen this before.  Will reload and report if the behavior repeats.

**Comment by majurg** [comment]
@johnmhoran Is this still an issue?

**Comment by johnmhoran** [comment]
Thanks for checking @majurg -- I haven't seen this behavior since my initial report (perhaps because I'm no longer trying to work with such large files).

**Comment by johnmhoran** [comment]
I haven't seen a repeat of this behavior since I opened the issue.  Closing.
