### ISSUE TITLE
Underscore in search seems to act like wildcard

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#317]
When searching for "i_Loader" (not using any quotes), I get numerous files and directories returned, none of which contains a match for that string.  One set of matches, for example, seems to have been returned because the path includes "...libloader...".  Just guessing but it may be that the underscore is interpreted as a wildcard character by Sequelize or SQLite.

**Comment by majurg** [comment]
#364 merged. Closing this.
