### ISSUE TITLE
Filter by Language not working correctly,

### ISSUE THREAD

**Issue by buxtonpaul** [nexB/scancode-workbench#320]
### Description
When trying to filter by language to examine particular types of file, the filter is not working correctly, it appear to be filtering if the chosen language is contained in the file detected language, which creates many false positives when you are trying to filter byt the C language
### Steps to reproduce
1. Scan a codebase which includes C files recognized file types that inlude the letter C e.g. Docker files.
2. Browse to the Table View
3. Activate Filters
4. Select The Language filter and choose C 

**Expected behavior**
List only C files

**Actual behavior**
Lists all files that have a Language type that includes the letter C e.g. Docker, Velocity, Batch file

**Reproduces how often:** 
100%

### System configuration
Unbuntu 16.04

**AboutCode Manager Version**:
Aboutcode-Manage 2.6.0

**ScanCode Toolkit Version**:
ScanCode version: 2.9.2.post308.ec97cb6

ScanCode options: {
  "input": "/user/pcb/local/workspace/powervr/swgraphics/rogueddk/MAIN/",
  "--copyright": true,
  "--generated": true,
  "--html-app": "scande.html",
  "--ignore": [
    "android"
  ],
  "--info": true,
  "--json": "scancode_rogue.json",
  "--license": true,
  "--license-policy": "imgpolicy.yml",
  "--package": true,
  "--processes": "8"
}
### Additional Information
Any additional information, configuration, or data that might be necessary to reproduce the issue. (i.e. screenshots and/or GIFs)

**Comment by majurg** [comment]
@buxtonpaul Thanks for this bug report. I will fix this issue shorty.

**Comment by majurg** [comment]
#321 merged, closing this.
