### ISSUE TITLE
Rename AboutCode Manager to ScanCode Workbench

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#324]
This is a placeholder Issue for renaming AboutCode Manager to ScanCode Workbench with the v3.0 release of ScanCode Workbench.  The focus on this needs to be on the externally visible elements of the product and documentation - we can refactor internals over a longer horizon. 

We also need to decide how closely to synch version numbering with ScanCode Toolkit - at the high level they should probably be synched for major and most minor releases.

**Comment by majurg** [comment]
#329 merged. Closing this ticket. If there are any AboutCode manager references that need to be cleaned up we can open another ticket.
