### ISSUE TITLE
Wrong values show when directories are closely named

### ISSUE THREAD

**Issue by steven-esser** [nexB/scancode-workbench#334]
![screen shot 2019-01-21 at 3 42 23 pm](https://user-images.githubusercontent.com/7485204/51504025-48c85f80-1d93-11e9-8a16-31d8f02e5e23.png)
![screen shot 2019-01-21 at 3 42 39 pm](https://user-images.githubusercontent.com/7485204/51504028-49f98c80-1d93-11e9-825e-14f2fcb777e1.png)

The above images show bugged behavior where an extra license value is detected, even though there should only be one license value being shown as detected. 

On first glance, this seems to be because both directories are similarly named. Our query is grabbing more data then is needed.

**Comment by majurg** [comment]
Moving this to Future milestone. This will require major refactoring and major schema changes to prevent bugs like this from occurring. Searching through a directory tree via path strings like we do currently does not work well at all and is probably a source of a lot of performance problems.

**Comment by amansheaven** [comment]
It's really a peculiar behaviour!! can I pick it up?? @majurg

**Comment by steven-esser** [comment]
@amansheaven Yes feel free. 

You may want to look at this for more detail as to what is needed: https://github.com/nexB/aboutcode/wiki/Project-Ideas-Improve-Workbench-Database-Schema

**Comment by OmkarPh** [comment]
Closing this, as it has been taken care of in the current implementation
