### ISSUE TITLE
Add Scan filename/SQLite filename to the Dashboard View 

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-workbench#336]
![screen shot 2019-01-28 at 3 43 41 pm](https://user-images.githubusercontent.com/7485204/51873831-7e30f800-2313-11e9-8d6f-996433c5a156.png)

Originally brought up by @DennisClark.

From the above image of the Dashboard View, there is a noticeable lack of what data source you are actually looking at. In order to correctly function as a Dashboard overview of Scan data, we need to add some prominent indication of the source Scan File name (or maybe the SQLite filename).

**Comment by mjherzog** [comment]
We need to show the Path for whatever the Dashboard is showing rather than repeating the name of the SQLite file which we already have on a top window bar. It might make sense to right justify the Path since it can be arbitrarily long and you do have the TreeView as a second reference point.

**Comment by majurg** [comment]
#348 merged. Closing this. 

The feature now works as follows:
* path is added after `"Dashboard - some/path/path.txt"`
* Overflow is handled by having ellipses on the left hand side of the text
