### ISSUE TITLE
Uploaded conclusions should be uploaded as Product Packages 

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-workbench#339]
Related: #338 

We currently upload Conclusions as Product Components. After completion of #338, we will need to change this functionality to upload Product Packages instead of Product Components, as we will now be focusing on Packages instead of Components.

**Comment by mjherzog** [comment]
See #413

**Comment by mjherzog** [comment]
Closing because we are deprecating Conclusions in SCWB in favor of building a more robust feature in SCIO.
