### ISSUE TITLE
Add Filter Reset button

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-workbench#353]
When you are working with multiple filters, it is often hard to track which filters are on and it can be extra work to reset current filters to "All".  In these cases I do not want to Clear the filters - I just want to reset them so that I do not need to re-Activate them which can be slow.

We should add a Reset Filters button that would reset the current Activated Filters to "All".

**Comment by vsvipul** [comment]
where should this filter be present. can someone guide me ?

**Comment by mjherzog** [comment]
It should probably be between the current Activate Filters and Clear Filters buttons.

**Comment by vsvipul** [comment]
can u please be more accurate so i can work on this. Doesn't Activate Filters already set all the filters to 'All'. ? @majurg @mjherzog

**Comment by mjherzog** [comment]
The goal is to reset the filter values to All without rerunning the full Activate Filters query which can be quite slow if you have many entries with dense data at the node where you are running Filters. In other words I want to keep the results of a prior Activate Filters query and just reset the selected Filter values to All against that dataset.

**Comment by majurg** [comment]
#363 merged. Closing this.
