### ISSUE TITLE
Improve initial JSON import file path handling

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-workbench#354]
### Description
When I import a JSON file, I then need to save this to a sqlite DB.
It would be great if the path and filename for the Sqlite Db file would be pre-populated to be the same as the as JSON file with sqlite extension. And in the same directory. This way I would not have to pick a new path. This is on Linux

### System configuration
**Operating System**:
Linux Ubuntu 16.04 x86_64 

**ScanCode Workbench Version**:
3.0.0b2

**Comment by majurg** [comment]
@pombredanne It should be filling in the correct name (Same as JSON file). Will look into creating it at the same path location; The MacOS version seems to do this by default, so I will test on Linux

**Comment by johnmhoran** [comment]
The Windows version seems to do this by default as well.

**Comment by pombredanne** [comment]
@johnmhoran @majurg thx
If this is only an issue on Linux, that's low priority then

**Comment by vsvipul** [comment]
@pombredanne prepopulates for me as well. I am running Ubuntu 18.10.

**Comment by majurg** [comment]
#362 Should fix this issue on Linux. Closing for now.
