### ISSUE TITLE
Enable/Allow to zoom in/out

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-workbench#356]
Since the WB is backed by a web browser, I would expect to be able to zoom in and out (Ctrl+ and Ctrl- typically) and this is not enabled. It would be great if it were

**Comment by vsvipul** [comment]
@pombredanne i have opened a pr. please preview.

**Comment by majurg** [comment]
@vsvipul See my PR review here: https://github.com/nexB/scancode-workbench/pull/357#pullrequestreview-210929753
