### ISSUE TITLE
Ability to display the API Key value in the "Upload Conclusions" form

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-workbench#391]
The "DejaCode API Key" field  in the "Upload Conclusions" form is always hidden. In order to double check the pasted value, it would be very useful to offer a "Display/Hide" toggle button, while keeping that value hidden by default.

Also, since the API Key never starts nor ends with a whitespace, it would be a good idea to "strip" leading and trailing whitespaces before making the API request. The would help with some copy/paste issues.

**Comment by majurg** [comment]
@tdruez The fix for this is merged in #394. I will leave this issue open until the next patch release of the workbench.

**Comment by steven-esser** [comment]
Patch release v3.1.1 of scancode-workbench is released and contains these fixes. Closing this ticket.
