### ISSUE TITLE
Allow empty Product.version in the "Upload Conclusions to DejaCode" from

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-workbench#392]
Product without a version value are possible in DejaCode but I cannot submit "Conclusions" to those Products since the Upload form does not allow the version field to be empty.

<img width="670" alt="Screen Shot 2019-09-19 at 8 37 58 PM" src="https://user-images.githubusercontent.com/489057/65271440-75e53180-db1d-11e9-93eb-e98bd63598b1.png">

**Comment by majurg** [comment]
@tdruez The fix for this is merged in #394. I will leave this issue open until the next patch release of the workbench.

**Comment by steven-esser** [comment]
Patch release v3.1.1 of scancode-workbench is released and contains these fixes. Closing this ticket.
