### ISSUE TITLE
The state of the conclusion view should be saved

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#7]
When a JSON file is exported and then reloaded into the app, the state of the conclusion view should be saved. It would be great if I could see the conclusion view in the same state as it was when I exported it (same position, same node expanded, etc.).

**Comment by jdaguil** [comment]
In order to be able to save a state about the node view position and the expanded nodes, we would have to store that information in possibly one of these options:

- The SQLite file. Although this would have all the difficulties that come with databases when the table structures change.
- Something like localStorage (a key-value storage, somehow based on the opened file name). This would probably be a better way to store this information because it’s more flexible to change, and it only sticks around per application installation rather than being something that is intrinsic to the SQLite file.

**Comment by majurg** [comment]
Conclusions are saved correctly on the Tree view and ConclusionDataTable view. We no longer have the node view so we can close this.
